### ISSUE TITLE
Create Routes for login and register.

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#69] opened 2020-03-03 19:24 UTC
Since, the UI for and signup page is noe updated. Update the routes in the back end and make the flow as per mentioned.

1. When user opens website, login page should appear.
2. If user logs in, go to home page . Otherwise, allow him to go to signup page.
3. After signing up, redirect to home page.

**Comment by anushreejain98** [comment] 2020-03-03 19:37
Hello @rajatmw1999 I would like to try solving this issue. Could you please assign me this.

**Comment by rajatmw1999** [comment] 2020-03-03 19:38
@anushreejain98 are you currently working on any other issue?

**Comment by anushreejain98** [comment] 2020-03-03 19:39
> @anushreejain98 are you currently working on any other issue?

no, I am not working on any other issue currently.

**Comment by rajatmw1999** [comment] 2020-03-03 19:41
Assign to @anushreejain98

**Comment by rajatmw1999** [comment] 2020-03-03 19:42
Try to fix this issue by today itself and put the PR.

**Comment by anushreejain98** [comment] 2020-03-03 19:42
> Assign to @anushreejain98

Thanks @rajatmw1999 I find that during signup, the register button does not work, no redirection is there.Is this what I need to resolve ?

**Comment by rajatmw1999** [comment] 2020-03-03 19:43
Read my comment above. Everything is mentioned there. And ya, make the register button work..

**Comment by anushreejain98** [comment] 2020-03-06 07:08
> Read my comment above. Everything is mentioned there. And ya, make the register button work..

Hello, the issue is fixed in current version, no need to create a PR

**Closed** 2020-03-06 08:21 UTC
Labels: easy, gssoc20, routes
